version: '2.1'

services:

  configserver:
    image: "repo-04.dodi.io:5000/configserver:0.0.1-SNAPSHOT"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GIT_URI: https://github.com/marceito2002/configServerPruebas.git
      #GIT_USER: alfonso.herreros
      #GIT_PASS: 
      HOSTNAME: "configserver"
    ports:
      - "8888:8888"
    
    networks:
     - docomo.fraudwall
    restart: always

  mongodb:
    image: mongo:latest
    command: --smallfiles 
    ports:
      - "27017:27017"
    networks:
      - docomo.fraudwall
    restart: always

  kafka:
    image: landoop/fast-data-dev
    container_name: kafka
    hostname: kafka
    ports:
     - "2181:2181"
     - "3030:3030"
     - "8081:8081"
     - "8082:8082"
     - "8083:8083"
     - "9092:9092"
    environment:
      ADV_HOST: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      SAMPLEDATA: 0
      BROWSECONFIGS: 1
      RUNTESTS: 0
      DEBUG: 1
    networks:
    - docomo.fraudwall


  partner:
    image: "repo-04.dodi.io:5000/partner:0.0.1-SNAPSHOT"
    container_name: partner
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_ENDPOINT: http://configserver:8888

    depends_on:      
      - configserver
      - mongodb
    ports:
      - "9090:9090"
    networks:
      - docomo.fraudwall


networks:
  docomo.fraudwall:
    driver: bridge