apiVersion: v1
kind: Service
metadata:
  labels:
    app: configserver
  name: configserver
  namespace: fraudwall
spec:
  ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    deploymentconfig: configserver
  type: ClusterIP